import type { StaticPage } from './types';

type PageSection = StaticPage['sections'][number];

const detail = (
  titleDe: string,
  titleEn: string,
  bodyDe: string,
  bodyEn: string,
  pointsDe: string[],
  pointsEn: string[],
): PageSection => ({
  title: { de: titleDe, en: titleEn },
  body: { de: bodyDe, en: bodyEn },
  points: { de: pointsDe, en: pointsEn },
});

export const pageEditorial: Record<string, PageSection[]> = {
  product: [
    detail(
      'Was am Ende sichtbar wird',
      'What becomes visible',
      'Der Atlas liefert kein magisches Match. Er macht einen nachvollziehbaren Arbeitsstand sichtbar: Welche Tätigkeiten interessieren dich, welche Wege hast du geprüft, was weißt du aus Quellen und welcher kleine Realitätstest kommt als Nächstes?',
      'The Atlas does not produce a magical match. It makes a traceable working position visible: which activities interest you, which routes you have checked, what is supported by sources and which small reality test comes next.',
      [
        'Gespeicherte Tätigkeiten statt nur abstrakter Berufstitel.',
        'Vergleich von Lernalltag, Zugang, Geld und Anschlusswegen.',
        'Offene Annahmen und Fragen bleiben sichtbar.',
        'Jeder Orientierungsweg endet mit einer überprüfbaren Handlung.',
      ],
      [
        'Saved activities rather than abstract job titles alone.',
        'Comparison of learning, entry, money and progression.',
        'Open assumptions and questions remain visible.',
        'Every exploration ends with a testable action.',
      ],
    ),
    detail(
      'Was das Produkt bewusst nicht verspricht',
      'What the product deliberately does not promise',
      'Berufsorientierung ist kontextabhängig. Deshalb garantieren wir weder Passung noch Ausbildungsplatz, ersetzen keine Beratungsfachkraft und stellen Daten nicht als vollständig oder zeitlos dar. Diese Grenzen sind Bestandteil des Produkts, nicht Kleingedrucktes.',
      'Career exploration depends on context. We therefore do not guarantee fit or a place, replace a professional adviser or present data as complete and timeless. These boundaries are part of the product, not fine print.',
      [
        'Keine Persönlichkeitsdiagnose aus wenigen Antworten.',
        'Keine bezahlte Platzierung einzelner Berufe oder Betriebe.',
        'Keine Gleichsetzung deutscher und britischer Qualifikationen.',
        'Keine automatische Bildungs- oder Bewerbungsentscheidung.',
      ],
      [
        'No personality diagnosis from a handful of answers.',
        'No paid placement of occupations or employers.',
        'No invented equivalence between German and UK qualifications.',
        'No automated education or application decision.',
      ],
    ),
  ],
  'how-it-works': [
    detail(
      'Ein Beispiel vom Signal zur Handlung',
      'An example from signal to action',
      '„Ich repariere gern Dinge“ wird nicht sofort zu „Du solltest Mechatroniker werden“. Der Atlas trennt das Signal in Fehlersuche, präzise Handarbeit und sichtbares Ergebnis, zeigt mehrere Arbeitsfelder und fordert anschließend einen Vergleich von zwei echten Aufgaben oder Betrieben.',
      '“I enjoy repairing things” does not immediately become “You should be a maintenance technician.” The Atlas separates fault-finding, precise practical work and visible outcomes, shows several environments and then asks for a comparison of two real tasks or employers.',
      [
        'Signal: konkrete Situation statt Selbstetikett.',
        'Hypothese: welche Tätigkeit daran interessant war.',
        'Optionen: mindestens zwei unterschiedliche Umgebungen.',
        'Test: Gespräch, Besuch, Aufgabe oder Bewerbung mit Termin.',
      ],
      [
        'Signal: a concrete situation, not a label.',
        'Hypothesis: which activity made it interesting.',
        'Options: at least two different environments.',
        'Test: a dated conversation, visit, task or application.',
      ],
    ),
    detail(
      'Erklärbar und veränderbar',
      'Explainable and revisable',
      'Jede vorgeschlagene Spur soll auf benennbare Eingaben und Informationen zurückgehen. Wenn du ein Interesse entfernst, eine Einschränkung ergänzt oder nach einem Praktikum anders denkst, muss sich die Karte verändern dürfen. Ein früher Stand wird nicht als dauerhafte Identität gespeichert.',
      'Every suggested trail should be traceable to named input and information. If you remove an interest, add a constraint or think differently after a placement, the map must be allowed to change. An early position is not stored as a permanent identity.',
      [
        'Begründung neben Vorschlag statt verstecktem Score.',
        'Unsicherheit wird ausgesprochen.',
        'Alternative Wege bleiben erreichbar.',
        'Nutzerfeedback kann eine Spur korrigieren oder entfernen.',
      ],
      [
        'Reason beside suggestion rather than a hidden score.',
        'Uncertainty is stated.',
        'Alternative routes remain accessible.',
        'User feedback can correct or remove a trail.',
      ],
    ),
  ],
  app: [
    detail(
      'Ein realistischer Nutzungsmoment',
      'A realistic moment of use',
      'Vor einem Beratungsgespräch speicherst du zwei Berufsfelder, markierst drei Fragen und vergleichst den Lernalltag. Im Gespräch öffnest du keine lange Ergebnisliste, sondern deine Karte. Danach notierst du den vereinbarten Betriebsbesuch und welche Annahme er prüfen soll.',
      'Before a careers conversation, you save two fields, mark three questions and compare the learning experience. In the conversation you open your map rather than a long result list. Afterwards you record the agreed employer visit and the assumption it should test.',
      [
        'Kurze Sessions statt Pflichtprofil in einem Durchgang.',
        'Speichern ohne öffentliche Darstellung.',
        'Vergleiche bleiben nach Kriterien nachvollziehbar.',
        'Eigene Fragen reisen in das nächste Gespräch mit.',
      ],
      [
        'Short sessions rather than one compulsory profile.',
        'Save without public display.',
        'Comparisons remain traceable to criteria.',
        'Your questions travel into the next conversation.',
      ],
    ),
    detail(
      'Standort und Benachrichtigungen',
      'Location and notifications',
      'Standortzugriff ist optional und soll nur dann angefragt werden, wenn eine regionale Funktion ihn unmittelbar braucht. Es gibt keine heimliche Dauerverfolgung. Benachrichtigungen sollen an selbst gewählte nächste Schritte erinnern, nicht Engagement um seiner selbst willen maximieren.',
      'Location is optional and should be requested only when a regional feature needs it at that moment. There is no hidden continuous tracking. Notifications should support self-chosen next actions, not maximise engagement for its own sake.',
      [
        'Region kann manuell gewählt werden.',
        'Berechtigung ist später widerrufbar.',
        'Kernorientierung funktioniert ohne Standort.',
        'Keine Streaks oder künstlicher Zeitdruck.',
      ],
      [
        'Region can be selected manually.',
        'Permission can be withdrawn later.',
        'Core exploration works without location.',
        'No streaks or artificial urgency.',
      ],
    ),
  ],
  'product-ai': [
    detail(
      'Ein guter AI-Moment',
      'A good AI moment',
      'Du fragst, worin sich zwei Ausbildungswege im Lernalltag unterscheiden. Die AI strukturiert die Unterschiede, nennt den Markt, zeigt Quellen und formuliert drei Fragen für Betrieb oder Beratung. Sie schließt nicht mit „Weg A passt besser zu dir“, wenn dafür keine belastbare Grundlage existiert.',
      'You ask how two routes differ in daily learning. AI structures the differences, names the market, provides sources and suggests three questions for an employer or adviser. It does not finish with “Route A is better for you” without a defensible basis.',
      [
        'Fakten und Vorschläge werden sprachlich getrennt.',
        'Markt und Geltungsbereich stehen bei Systemaussagen.',
        'Quellen führen zur tatsächlich relevanten Stelle.',
        'Unsicherheit erzeugt eine Prüffrage statt erfundener Gewissheit.',
      ],
      [
        'Facts and suggestions are separated in language.',
        'System claims name market and scope.',
        'Sources lead to the relevant evidence.',
        'Uncertainty creates a check question rather than fake confidence.',
      ],
    ),
    detail(
      'Wann ein Mensch übernehmen muss',
      'When a person must take over',
      'Schutz, Diskriminierung, akute Belastung, individuelle Rechtsfragen und verbindliche Zulassungsentscheidungen gehören nicht in eine freie AI-Antwort. Das Produkt soll dann die Grenze benennen, sensible Details nicht unnötig abfragen und einen geeigneten menschlichen Kontaktweg zeigen.',
      'Safeguarding, discrimination, acute distress, individual legal questions and binding eligibility decisions do not belong in an open AI answer. The product should state the boundary, avoid requesting unnecessary sensitive detail and show an appropriate human route.',
      [
        'Keine Diagnose oder Krisenberatung.',
        'Keine Empfehlung, Vorfälle geheim zu halten.',
        'Keine verbindliche Vertrags- oder Rechtsauslegung.',
        'Sichtbarer Weg zu Beratung, Schutzkontakt oder offizieller Stelle.',
      ],
      [
        'No diagnosis or crisis counselling.',
        'No suggestion to keep concerns secret.',
        'No binding contract or legal interpretation.',
        'Visible route to guidance, safeguarding or an official body.',
      ],
    ),
  ],
  'data-sources': [
    detail(
      'Unsere Quellenhierarchie',
      'Our source hierarchy',
      'Für Systemregeln beginnen wir bei der zuständigen Behörde oder dem gesetzlich beauftragten Institut. Für Berufsprofile nutzen wir offizielle Standards und Berufsservices. Redaktionelle Erklärungen dürfen diese Quellen verständlicher machen, aber weder Zuständigkeit noch Einschränkung entfernen.',
      'For system rules we start with the accountable authority or mandated institute. For occupations we use official standards and careers services. Editorial explanation may make those sources easier to understand but must not remove authority or limitation.',
      [
        '1. Gesetz, Regelwerk oder zuständige Primärquelle.',
        '2. Offizieller Berufsstandard oder öffentlicher Careers Service.',
        '3. Eigene redaktionelle Einordnung mit Review.',
        '4. Sekundärquelle nur als Ergänzung, klar benannt.',
      ],
      [
        '1. Law, rule or accountable primary source.',
        '2. Official occupational standard or public careers service.',
        '3. Our reviewed editorial explanation.',
        '4. Clearly labelled secondary source only as context.',
      ],
    ),
    detail(
      'Was bei einem Widerspruch passiert',
      'What happens when sources conflict',
      'Wir wählen nicht still die bequemste Aussage. Redaktion prüft Zuständigkeit, Markt, Datum und mögliche Übergangsregel. Bis zur Klärung wird die Aussage eingeschränkt oder entfernt. Änderungen an wesentlichen Inhalten lösen Review und Cache-Aktualisierung für die betroffene Sprachfassung aus.',
      'We do not silently choose the most convenient claim. Editors check authority, market, date and any transition rule. Until resolved, the statement is limited or removed. Material changes trigger review and cache refresh for the affected language version.',
      [
        'Konflikt und betroffene Seiten inventarisieren.',
        'Primärquelle und fachliche Zuständigkeit klären.',
        'Korrektur mit Datum und Auswirkung dokumentieren.',
        'Übersetzung separat prüfen statt automatisch mitzuändern.',
      ],
      [
        'Inventory the conflict and affected pages.',
        'Resolve primary authority and scope.',
        'Document correction, date and impact.',
        'Review the translation separately rather than changing it blindly.',
      ],
    ),
  ],
  'young-people': [
    detail(
      'Du behältst die Kontrolle',
      'You remain in control',
      'Du kannst eine Spur speichern, ändern oder verwerfen. Eine anfängliche Antwort wird nicht zur festen Aussage über deine Persönlichkeit. Wenn eine Empfehlung unpassend wirkt, sollst du die Begründung sehen und widersprechen können – nicht deine Erfahrung an einen Score anpassen müssen.',
      'You can save, revise or discard a trail. An early answer does not become a fixed statement about your personality. If a suggestion feels wrong, you should be able to see the reason and challenge it rather than adjusting your experience to fit a score.',
      [
        'Du darfst „weiß ich noch nicht“ antworten.',
        'Du kannst Standort und optionale Angaben weglassen.',
        'Du bekommst mehrere Wege statt eines Siegers.',
        'Du kannst Informationen mit einer Vertrauensperson prüfen.',
      ],
      [
        'You may answer “I do not know yet”.',
        'You can omit location and optional details.',
        'You receive several routes rather than one winner.',
        'You can check information with a trusted person.',
      ],
    ),
    detail(
      'Beginne in 20 Minuten',
      'Start in 20 minutes',
      'Wähle eine Tätigkeit, die du gern oder ungern gemacht hast. Beschreibe, was genau passiert ist. Suche zwei Berufsfelder, in denen ein ähnlicher Teil vorkommt, und speichere je eine Frage zum echten Alltag. Damit hast du noch keine Wahl getroffen – aber einen brauchbaren Startpunkt gebaut.',
      'Choose one activity you enjoyed or disliked and describe what actually happened. Find two fields where a similar activity appears and save one question about real daily work for each. You have not made a choice, but you have built a useful starting point.',
      [
        'Eine konkrete Erfahrung auswählen.',
        'Interessanten oder schwierigen Teil benennen.',
        'Zwei unterschiedliche Umgebungen finden.',
        'Einen Realitätstest mit Datum planen.',
      ],
      [
        'Choose one concrete experience.',
        'Name the interesting or difficult part.',
        'Find two different environments.',
        'Plan one dated reality test.',
      ],
    ),
  ],
  schools: [
    detail(
      'Einbettung statt Zusatztool',
      'Integration rather than another tool',
      'Ein Pilot beginnt bei einem bestehenden Ablauf: Vor- und Nachbereitung eines Gesprächs, Berufsfeldrecherche im Unterricht oder Reflexion eines Betriebsbesuchs. Apprentice Atlas ersetzt weder Curriculum noch professionelle Dokumentation. Wir definieren, an welcher Stelle das Produkt Arbeit erleichtert und wo es bewusst endet.',
      'A pilot starts inside an existing workflow: preparation and follow-up for a conversation, classroom career research or reflection after an employer visit. Apprentice Atlas replaces neither the curriculum nor professional records. We define where it reduces friction and where it deliberately stops.',
      [
        'Konkreter Nutzungsmoment und zuständige Person.',
        'Vorhandene Schutz- und Einwilligungsprozesse übernehmen.',
        'Keine sensiblen Beratungsnotizen in Analytics.',
        'Alternative ohne eigenes Gerät oder Analytics-Zustimmung.',
      ],
      [
        'Concrete use moment and accountable person.',
        'Use existing safeguarding and consent processes.',
        'No sensitive guidance notes in analytics.',
        'An alternative without a personal device or analytics consent.',
      ],
    ),
    detail(
      'Was Beratende sehen – und nicht sehen',
      'What advisers see—and do not see',
      'Zum Launch gibt es kein Schul-Dashboard und keine verdeckte Lernendenüberwachung. Jugendliche können ihre Karte freiwillig in ein Gespräch mitbringen. Aggregate Pilotdaten werden nur für vorher definierte Lernfragen genutzt und nicht zur individuellen Leistungsbewertung.',
      'At launch there is no school dashboard and no hidden learner monitoring. Young people may choose to bring their map into a conversation. Aggregate pilot data is used only for agreed learning questions, not individual performance assessment.',
      [
        'Keine Rangliste von Lernenden oder Klassen.',
        'Keine Weitergabe freier Texte an Schulen als Standard.',
        'Keine automatisierte Risikoklassifizierung.',
        'Klarer Kontakt für Korrektur, Vorfall und Rücknahme.',
      ],
      [
        'No ranking of learners or classes.',
        'No default sharing of free text with schools.',
        'No automated risk classification.',
        'Clear contact for correction, incident and withdrawal.',
      ],
    ),
  ],
  parents: [
    detail(
      'Was Sie gemeinsam prüfen können',
      'What you can check together',
      'Nutzen Sie den Atlas nicht als Beweis dafür, welcher Weg „richtig“ ist. Öffnen Sie zwei konkrete Optionen und prüfen Sie gemeinsam Wochenablauf, Lernorte, Vergütung oder Kosten, Zugang, Unterstützung und Anschluss. Markieren Sie, was belegt ist und was noch aus einem Gespräch stammt.',
      'Do not use the Atlas as proof of one “right” route. Open two concrete options and examine weekly life, learning locations, pay or cost, entry, support and progression together. Mark what is evidenced and what still needs a conversation.',
      [
        'Eine Frage stellen, bevor Sie Rat geben.',
        'Eigene Sorge als Sorge kennzeichnen, nicht als Fakt.',
        'Vertrag und Trainingsplan vor Unterschrift lesen.',
        'Bei Schutzthemen die benannten offiziellen Wege nutzen.',
      ],
      [
        'Ask one question before giving advice.',
        'Label your concern as concern rather than fact.',
        'Read the contract and training plan before signing.',
        'Use named official routes for safeguarding concerns.',
      ],
    ),
    detail(
      'Datenschutz für Familien',
      'Privacy for families',
      'Die Marketing-Vormerkliste ist ab 16 direkt zugänglich; Jüngere werden zur Anmeldung durch Eltern oder Erziehungsberechtigte geführt. Das ist keine allgemeine Altersfreigabe für jede spätere Produktfunktion. Vor App-Launch werden Einwilligung, Schutz und Rechtsgrundlage je Funktion gesondert geprüft.',
      'Direct marketing waitlist sign-up is available from 16; younger people are directed to a parent or carer. This is not a blanket age decision for every future product feature. Consent, safeguarding and lawful basis will be reviewed separately for each function before app launch.',
      [
        'Keine Werbung auf Basis persönlicher Orientierung.',
        'Analytics nur nach ausdrücklicher Zustimmung.',
        'Standort ist optional.',
        'Löschfristen und Kontaktweg sind veröffentlicht.',
      ],
      [
        'No advertising based on personal exploration.',
        'Analytics only after explicit consent.',
        'Location is optional.',
        'Retention and contact routes are published.',
      ],
    ),
  ],
  pilot: [
    detail(
      'So sieht ein erster Pilot aus',
      'What an initial pilot looks like',
      'Ein Pilot ist eine begrenzte Erprobung, kein stiller Rollout. Partner und Estopia legen Zielgruppe, Nutzungsmoment, Dauer, Unterstützung, Schutzweg, minimale Daten und Entscheidungszeitpunkt schriftlich fest. Umfang und Laufzeit werden erst nach gemeinsamer Machbarkeits- und Datenschutzprüfung bestätigt.',
      'A pilot is a bounded test, not a quiet rollout. The partner and Estopia document the audience, use moment, duration, support, safeguarding route, minimum data and decision point. Scale and timing are confirmed only after a joint feasibility and privacy review.',
      [
        'Ein klarer Anwendungsfall statt Nutzung „überall“.',
        'Benannte Verantwortliche auf beiden Seiten.',
        'Briefing für Mitarbeitende, Lernende und Eltern.',
        'Stop- und Eskalationskriterien vor dem ersten Einsatz.',
      ],
      [
        'One clear use case rather than use “everywhere”.',
        'Named accountable people on both sides.',
        'Briefing for staff, learners and parents.',
        'Stopping and escalation criteria before first use.',
      ],
    ),
    detail(
      'Was Partner am Ende erhalten',
      'What partners receive at the end',
      'Der Abschluss trennt beobachtete Nutzung, Rückmeldungen, mögliche Lernsignale, Vorfälle und offene Grenzen. Partner erhalten keine werbliche Erfolgsgeschichte, sondern eine Entscheidungsgrundlage: fortführen, verändern, weiter untersuchen oder stoppen.',
      'The close-out separates observed use, feedback, possible learning signals, incidents and unresolved limits. Partners receive a decision document rather than a promotional success story: continue, change, investigate further or stop.',
      [
        'Vereinbarte Kennzahlen mit Kontext.',
        'Qualitative Rückmeldungen ohne unnötige Identifizierung.',
        'Dokumentierte Abweichungen und negative Ergebnisse.',
        'Empfehlung mit Unsicherheit und verantwortlicher Entscheidung.',
      ],
      [
        'Agreed measures with context.',
        'Qualitative feedback without unnecessary identification.',
        'Documented exceptions and negative findings.',
        'A recommendation with uncertainty and accountable decision.',
      ],
    ),
  ],
  'privacy-safety': [
    detail(
      'Datenflüsse zum Launch',
      'Launch data flows',
      'Die öffentliche Seite kann ohne Konto genutzt werden. Das Partnerformular speichert Organisations- und Kontaktdaten zur Bearbeitung einer Anfrage. Die Vormerkliste speichert E-Mail, Markt, Plattform, Einwilligungsversion und Zeitpunkte. Analytics wird separat und erst nach Zustimmung geladen; Suchbegriffe und Formulartexte werden nicht als Event-Eigenschaften versendet.',
      'The public site works without an account. The partner form stores organisation and contact details to handle an enquiry. The waitlist stores email, market, platform, consent version and timestamps. Analytics loads separately and only after consent; search terms and form messages are not sent as event properties.',
      [
        'Keine CMS- oder Lead-Tabelle über die öffentliche Data API.',
        'Keine Service-Secrets im Browser.',
        'Serverseitige Validierung, Bot-Schutz und Rate-Limits.',
        'Getrennte Staging- und Produktionsprojekte.',
      ],
      [
        'No CMS or lead table through the public Data API.',
        'No service secrets in the browser.',
        'Server-side validation, bot protection and rate limits.',
        'Separate staging and production projects.',
      ],
    ),
    detail(
      'Wenn etwas schiefgeht',
      'When something goes wrong',
      'Sicherheits- und Datenschutzmeldungen werden nach Auswirkung priorisiert. Betroffene Verarbeitung kann gestoppt, ein Schlüssel rotiert oder eine Funktion zurückgenommen werden. Gesetzliche Melde- und Informationspflichten werden mit qualifizierter Beratung geprüft. Vor Launch folgt eine juristische Prüfung einschließlich Kinder-Datenschutz und DPIA-Bedarf.',
      'Security and privacy reports are prioritised by impact. Affected processing can be stopped, a key rotated or a feature withdrawn. Statutory notification duties are assessed with qualified advice. Legal review before launch includes children’s privacy and the need for a DPIA.',
      [
        'security@ für technische Schwachstellen.',
        'privacy@ für Betroffenenrechte und Datenfragen.',
        'Nachvollziehbare Incident-Zeitleiste.',
        'Keine öffentliche Launchfreigabe vor Legal Gate.',
      ],
      [
        'security@ for technical vulnerabilities.',
        'privacy@ for rights and data questions.',
        'Traceable incident timeline.',
        'No public launch approval before the legal gate.',
      ],
    ),
  ],
  'responsible-ai': [
    detail(
      'Risikoprüfung entlang einer Antwort',
      'Risk checks across an answer',
      'Wir prüfen nicht nur das Modell, sondern den gesamten Weg: Welche Eingabe wird verlangt, welcher Quellenkontext wird beigefügt, wie wird Unsicherheit formuliert, welche Handlung schlägt die Oberfläche vor und wie kann ein Fehler gemeldet werden? Ein gutes Modell kann in einem schlechten Interface trotzdem Schaden verursachen.',
      'We assess more than the model: what input is requested, which source context is supplied, how uncertainty is expressed, which action the interface suggests and how an error can be reported. A capable model can still cause harm inside a poor interface.',
      [
        'Testfälle in Deutsch und britischem Englisch.',
        'Vergleich über Geschlecht, Herkunftssignale und Bildungswege.',
        'Besondere Tests für Minderjährige und Schutzsituationen.',
        'Review nach Modell-, Prompt- oder Quellenänderung.',
      ],
      [
        'Tests in German and British English.',
        'Comparison across gender, background signals and education routes.',
        'Specific tests for minors and safeguarding situations.',
        'Review after model, prompt or source changes.',
      ],
    ),
    detail(
      'Beschwerde und Korrektur',
      'Complaint and correction',
      'Nutzende müssen eine problematische Antwort melden können, ohne sie öffentlich zu machen. Das Team trennt faktischen Fehler, unangemessene Empfehlung, Sicherheitsproblem und Produktmissverständnis. Je nach Typ werden Quelle, Prompt, Darstellung oder Funktionsgrenze korrigiert.',
      'People must be able to report a problematic answer without publishing it. The team separates factual error, inappropriate suggestion, safety concern and product misunderstanding. The source, prompt, presentation or feature boundary is corrected according to the issue.',
      [
        'Meldung mit minimal notwendigem Kontext.',
        'Keine Nutzung sensibler Meldungen als Marketingbeispiel.',
        'Wiederholungstest vor Freigabe der Korrektur.',
        'Schwere Muster können zur Abschaltung führen.',
      ],
      [
        'Report with the minimum necessary context.',
        'No use of sensitive reports as marketing examples.',
        'Regression test before releasing a correction.',
        'Serious patterns can lead to withdrawal.',
      ],
    ),
  ],
  'data-principles': [
    detail(
      'Die fünf Regeln vollständig',
      'The five rules in full',
      'Neben Zuständigkeit, Kontext und Korrigierbarkeit gelten Datensparsamkeit und Trennung von Beobachtung und Schlussfolgerung. Wir sammeln nicht vorsorglich alles, was später nützlich sein könnte. Und wir lassen aus einem Nutzungsereignis keine Aussage über Motivation oder Eignung entstehen.',
      'Alongside authority, context and correctability, we apply data minimisation and separation of observation from inference. We do not collect everything just in case it becomes useful. A usage event does not become a claim about motivation or suitability.',
      [
        'Zuständigkeit: Wer darf diese Aussage verbindlich treffen?',
        'Kontext: Wo, wann und für wen gilt sie?',
        'Sparsamkeit: Brauchen wir das Feld wirklich?',
        'Trennung: Was wurde beobachtet, was nur abgeleitet?',
        'Korrigierbarkeit: Wer prüft und ändert?',
      ],
      [
        'Authority: who can make this claim?',
        'Context: where, when and for whom does it apply?',
        'Minimisation: do we genuinely need the field?',
        'Separation: what was observed and what was inferred?',
        'Correctability: who reviews and changes it?',
      ],
    ),
    detail(
      'Praktische Entscheidung',
      'A practical decision',
      'Ein Suchbegriff könnte für Produktanalyse interessant sein, kann aber persönliche Sorgen oder sensible Informationen enthalten. Deshalb messen wir, dass eine Suche stattgefunden hat, nicht den freien Text als Analytics-Eigenschaft. Inhaltliche Verbesserung erfolgt über kontrollierte, freiwillige Forschung statt verdeckter Sammlung.',
      'A search phrase might appear useful for product analysis but can contain personal concerns or sensitive information. We therefore measure that a search happened, not its free text as an analytics property. Content improvement uses controlled voluntary research rather than hidden collection.',
      [
        'Zweck vor Erhebung notieren.',
        'Weniger eingriffsintensive Alternative prüfen.',
        'Zugriff und Löschfrist festlegen.',
        'Neue Nutzung erfordert neue Prüfung.',
      ],
      [
        'Record purpose before collection.',
        'Check a less intrusive alternative.',
        'Set access and retention.',
        'A new use requires a new review.',
      ],
    ),
  ],
  accessibility: [
    detail(
      'Was wir tatsächlich testen',
      'What we actually test',
      'Automatisierte Prüfungen finden nur einen Teil der Barrieren. Zentrale Templates werden zusätzlich vollständig per Tastatur bedient, bei 200 Prozent Zoom geprüft und mit Screenreader auf Struktur, Namen, Statusmeldungen und Fehlerführung kontrolliert. Reduced Motion entfernt den orchestrierten Seitenauftakt und die Weglinienbewegung.',
      'Automated checks find only some barriers. Core templates are also completed by keyboard, checked at 200% zoom and reviewed with a screen reader for structure, names, status messages and error guidance. Reduced Motion removes the orchestrated entrance and route-line movement.',
      [
        'Navigation, Formulare, Consent und Ressourcensuche.',
        '360, 390, 768, 1280 und 1440 Pixel.',
        'Chromium, Firefox und WebKit.',
        'Deutsch und Englisch mit realen Textlängen.',
      ],
      [
        'Navigation, forms, consent and resource search.',
        '360, 390, 768, 1280 and 1440 pixels.',
        'Chromium, Firefox and WebKit.',
        'German and English with real text length.',
      ],
    ),
    detail(
      'Barrieren melden',
      'Report a barrier',
      'Eine hilfreiche Meldung nennt Seite, Aufgabe, verwendetes Gerät oder Hilfsmittel und was statt des erwarteten Ergebnisses geschah. Ein Screenshot ist optional. Teilen Sie keine sensiblen Daten. Wir bestätigen die Meldung und nennen nach Prüfung Auswirkung, Zwischenlösung und nächsten Schritt.',
      'A useful report names the page, task, device or assistive technology and what happened instead of the expected result. A screenshot is optional. Do not share sensitive data. We acknowledge the report and, after review, provide impact, workaround and next action.',
      [
        'E-Mail: accessibility@apprenticeatlas.com.',
        'Kritische Blockade wird vor kosmetischem Fehler priorisiert.',
        'Korrektur erhält einen Regressionstest.',
        'Bekannte Abweichungen erscheinen in der Erklärung.',
      ],
      [
        'Email: accessibility@apprenticeatlas.com.',
        'A critical blocker is prioritised over a cosmetic issue.',
        'The correction receives a regression test.',
        'Known exceptions appear in the statement.',
      ],
    ),
  ],
  impact: [
    detail(
      'Unsere Wirkungskette',
      'Our impact chain',
      'Wir erwarten nicht, dass eine einzelne App-Nutzung direkt einen Ausbildungsabschluss verursacht. Der plausible Weg beginnt kleiner: verständlichere Optionen, bessere Fragen, ein geplanter Realitätstest und informiertere Gespräche. Erst danach können Bewerbungs- und Übergangsergebnisse betrachtet werden – mit den vielen externen Einflüssen, die dazugehören.',
      'We do not expect a single app session to cause apprenticeship completion. The plausible chain starts smaller: clearer options, better questions, a planned reality test and more informed conversations. Application and transition outcomes can be considered later, with the many external influences they contain.',
      [
        'Input: Zugang, Material und Begleitung.',
        'Aktivität: erkunden, vergleichen, fragen, planen.',
        'Frühes Ergebnis: Orientierungskompetenz und Handlung.',
        'Späteres Ergebnis: Übergang, Verbleib und Entwicklung.',
      ],
      [
        'Input: access, material and support.',
        'Activity: explore, compare, question and plan.',
        'Early outcome: career-management skill and action.',
        'Later outcome: transition, persistence and progression.',
      ],
    ),
    detail(
      'Welche Aussage wir nicht machen',
      'Claims we will not make',
      'Wenn 70 Prozent einer Pilotgruppe eine Ressource öffnen, haben wir Nutzung beobachtet – nicht bessere Entscheidungen. Wenn Teilnehmende anschließend klarere Fragen formulieren, kann das ein Lernsignal sein, aber ohne geeignetes Design keine kausale Wirkung. Berichte benennen diese Grenze ausdrücklich.',
      'If 70 per cent of a pilot group open a resource, we have observed use—not better decisions. If participants then formulate clearer questions, that may be a learning signal but is not causal impact without a suitable design. Reports state that boundary explicitly.',
      [
        'Keine Kausalität aus Vorher-Nachher allein.',
        'Keine Erfolgsquote ohne Nenner und Teilnahmebeschreibung.',
        'Keine Ausblendung von Nichtnutzung oder Abbruch.',
        'Keine nachträgliche Änderung der Hauptfrage, um Erfolg zu zeigen.',
      ],
      [
        'No causality from before-and-after alone.',
        'No success rate without denominator and participation context.',
        'No hiding non-use or dropout.',
        'No changing the main question afterwards to manufacture success.',
      ],
    ),
  ],
  about: [
    detail(
      'Verantwortung im Unternehmen',
      'Accountability in the company',
      'Estopia Engineering Ltd verantwortet Produkt und Betrieb. Inhalte brauchen Autor, Reviewer, Quellen und nächstes Prüfdatum. Technische Funktionen erhalten einen Owner, Monitoring und Rücknahmeweg. Für juristische, fachliche und Schutzfragen arbeiten wir vor Launch mit entsprechend qualifizierter externer Prüfung.',
      'Estopia Engineering Ltd is accountable for product and operation. Content requires an author, reviewer, sources and next review date. Technical functions have an owner, monitoring and a withdrawal route. Legal, professional and safeguarding matters receive appropriately qualified external review before launch.',
      [
        'Keine anonymen institutionellen Behauptungen.',
        'Korrekturwege für Inhalt, Datenschutz und Barrierefreiheit.',
        'Getrennte Verantwortlichkeit für Veröffentlichung und Übersetzung.',
        'Pilotentscheidung vor Skalierung.',
      ],
      [
        'No anonymous institutional claims.',
        'Correction routes for content, privacy and accessibility.',
        'Separate accountability for publication and translation.',
        'Pilot decision before scale.',
      ],
    ),
    detail(
      'Woran wir uns messen lassen wollen',
      'What we want to be judged by',
      'Nicht an der Länge einer Featureliste, sondern daran, ob ein junger Mensch eine Möglichkeit besser versteht, eine gute Frage stellen und einen nächsten Schritt selbst wählen kann – ohne dafür unnötig persönliche Daten abzugeben oder einer undurchsichtigen Empfehlung vertrauen zu müssen.',
      'Not by the length of a feature list, but by whether a young person can understand an option, ask a useful question and choose a next action—without surrendering unnecessary personal data or trusting an opaque recommendation.',
      [
        'Verständlichkeit ohne falsche Vereinfachung.',
        'Quellen und Grenzen an der Aussage.',
        'Handlungsfähigkeit statt Engagement-Metrik.',
        'Korrektur und Rücknahme als normale Produktarbeit.',
      ],
      [
        'Clarity without false simplification.',
        'Sources and limits beside the claim.',
        'Agency rather than engagement metrics.',
        'Correction and withdrawal as normal product work.',
      ],
    ),
  ],
  story: [
    detail(
      'Was der Hackathon bewiesen hat',
      'What the hackathon established',
      'Der Prototyp zeigte, dass sich Berufsorientierung als kartografische Erkundung verständlich erzählen lässt und dass Mobile, offizielle Informationen und AI-Unterstützung technisch zusammenspielen können. Er bewies nicht, dass Empfehlungen fair, Inhalte vollständig oder der Dienst schon für Schulen betriebsbereit waren.',
      'The prototype showed that career exploration can be explained as mapping and that mobile interaction, official information and AI support can work together technically. It did not prove that suggestions were fair, content complete or the service ready for schools.',
      [
        'Belegt: verständliche Produktidee und technische Machbarkeit.',
        'Offen: Bedarf und Wirkung in realen Kontexten.',
        'Offen: Governance, Schutz und dauerhafter Betrieb.',
        'Offen: Qualität über Märkte und Sprachen hinweg.',
      ],
      [
        'Established: a clear product idea and technical feasibility.',
        'Open: need and impact in real contexts.',
        'Open: governance, safeguarding and sustained operation.',
        'Open: quality across markets and languages.',
      ],
    ),
    detail(
      'Der Weg zur öffentlichen Freigabe',
      'The route to public release',
      'Die Plattform geht erst öffentlich live, wenn Inhalte, Formulare, Datenschutz, Barrierefreiheit, Infrastruktur und Rückkehr auf einen vorherigen Stand gemeinsam abgenommen sind. Pilotpartnerschaft kommt vor breiter Wirkungsaussage; echte Evidenz kommt vor Wachstumsrhetorik.',
      'The platform goes public only after content, forms, privacy, accessibility, infrastructure and rollback have passed together. Pilot partnership comes before broad impact claims; real evidence comes before growth rhetoric.',
      [
        'Redaktionelle Bibliothek und Quellenreview.',
        'Juristische Prüfung und DPIA-Entscheidung.',
        'Barrierefreiheits- und Security-Abnahme.',
        'Staging, Migration, Smoke-Test und Rollback.',
      ],
      [
        'Editorial library and source review.',
        'Legal review and DPIA decision.',
        'Accessibility and security sign-off.',
        'Staging, migration, smoke test and rollback.',
      ],
    ),
  ],
  press: [
    detail(
      'Belegbare Kernfakten',
      'Verifiable core facts',
      'Apprentice Atlas ist eine in Entwicklung befindliche zweisprachige Plattform für berufliche Orientierung in Deutschland und dem Vereinigten Königreich. Das Produkt verbindet redaktionelle Ressourcen, offizielle Quellen, App-gestützte Erkundung und begrenzte AI-Unterstützung. Eine öffentliche Wirkung ist noch nicht nachgewiesen.',
      'Apprentice Atlas is a bilingual careers exploration platform in development for Germany and the United Kingdom. It combines editorial resources, official sources, app-supported exploration and bounded AI assistance. Public impact has not yet been established.',
      [
        'Status: Pre-Launch und Pilotvorbereitung.',
        'Unternehmen: Estopia Engineering Ltd.',
        'Märkte: Deutschland und UK mit systemspezifischen Inhalten.',
        'Keine freigegebenen Partner- oder Wirkungszahlen.',
      ],
      [
        'Status: pre-launch and pilot preparation.',
        'Company: Estopia Engineering Ltd.',
        'Markets: Germany and the UK with system-specific content.',
        'No approved partner or impact figures.',
      ],
    ),
    detail(
      'Materialnutzung',
      'Using brand material',
      'Freigegebene Logos und Screens dürfen nicht so verändert werden, dass eine Partnerschaft, Zertifizierung oder Live-Funktion suggeriert wird. Produktaufnahmen werden mit Versionsdatum geliefert. Dokumentarische Fotos erhalten eine eigene Lizenz- und Credit-Angabe.',
      'Approved logos and screenshots must not be altered to imply partnership, certification or a live function. Product captures are supplied with a version date. Documentary photography carries its own licence and credit record.',
      [
        'Produktname nicht abkürzen oder übersetzen.',
        'Keine nachgebauten Screens mit erfundenen Daten.',
        'Credits und Nutzungsumfang beibehalten.',
        'Faktencheck vor Veröffentlichung an press@.',
      ],
      [
        'Do not abbreviate or translate the product name.',
        'No recreated screens with invented data.',
        'Retain credits and permitted use.',
        'Send factual checks to press@ before publication.',
      ],
    ),
  ],
  contact: [
    detail(
      'Damit wir richtig antworten können',
      'Help us route your enquiry',
      'Nennen Sie bei Pilotinteresse Organisation, Rolle, Land, Zielgruppe und den konkreten Nutzungskontext. Für Korrekturen reichen Seitenlink, problematische Aussage und möglichst die bessere Primärquelle. Senden Sie keine sensiblen Daten von Jugendlichen über das allgemeine Kontaktpostfach.',
      'For pilot enquiries, include organisation, role, country, audience and the intended use context. For corrections, provide the page, disputed claim and ideally a better primary source. Do not send sensitive information about young people to the general inbox.',
      [
        'Pilot: Partnerformular.',
        'Inhalt: corrections@apprenticeatlas.com.',
        'Sicherheit: security@apprenticeatlas.com.',
        'Datenschutz: privacy@apprenticeatlas.com.',
      ],
      [
        'Pilot: partner form.',
        'Content: corrections@apprenticeatlas.com.',
        'Security: security@apprenticeatlas.com.',
        'Privacy: privacy@apprenticeatlas.com.',
      ],
    ),
    detail(
      'Was als Nächstes passiert',
      'What happens next',
      'Partneranfragen werden geprüft und einer verantwortlichen Person zugeordnet. Wir versprechen auf dieser Pre-Launch-Seite keine feste Antwortzeit, bevor der Supportbetrieb final besetzt ist. Sicherheits- und Datenschutzmeldungen werden nach möglicher Auswirkung priorisiert.',
      'Partner enquiries are reviewed and assigned to an accountable person. This pre-launch site does not promise a response time before support operations are fully staffed. Security and privacy reports are prioritised by potential impact.',
      [
        'Eingangsbestätigung nach erfolgreicher Formularverarbeitung.',
        'Rückfrage nur zu notwendigen Angaben.',
        'Keine Aufnahme in Newsletter oder CRM ohne eigenen Zweck.',
        'Löschung nach veröffentlichter Retention-Regel.',
      ],
      [
        'Receipt after successful form processing.',
        'Follow-up only for necessary information.',
        'No newsletter or CRM enrolment without a separate purpose.',
        'Deletion under the published retention rule.',
      ],
    ),
  ],
};
