import type { StaticPage } from './types';

type PageSection = StaticPage['sections'][number];

const detail = (
  titleDe: string,
  titleEn: string,
  bodyDe: string,
  bodyEn: string,
  pointsDe: string[],
  pointsEn: string[],
): PageSection => ({
  title: { de: titleDe, en: titleEn },
  body: { de: bodyDe, en: bodyEn },
  points: { de: pointsDe, en: pointsEn },
});

export const pageEditorial: Record<string, PageSection[]> = {
  product: [
    detail(
      'Dein Weg auf einen Blick',
      'Your journey at a glance',
      'Apprentice Atlas verbindet deine Suche, gespeicherte Stellen und Bewerbungen zu einem persönlichen Arbeitsbereich. Du siehst, welche Chancen du entdeckt hast, was für sie spricht, welche Frist als Nächstes ansteht und wo du im Bewerbungsprozess gerade bist.',
      'Apprentice Atlas connects discovery, saved opportunities and applications in one personal workspace. You can see what you found, why each opportunity matters, which deadline comes next and where every application currently stands.',
      [
        'Offizielle Stellen auf Karte und Liste entdecken.',
        'Favoriten mit Aufgaben, Ort und Anforderungen vergleichen.',
        'Bewerbungsstatus, Interviews und Fristen verfolgen.',
        'Fortschritt teilen oder als PDF exportieren.',
      ],
      [
        'Discover official opportunities on a map and list.',
        'Compare favourites by duties, location and requirements.',
        'Track application status, interviews and deadlines.',
        'Share progress or export it as a PDF.',
      ],
    ),
    detail(
      'Von der Stelle zum Bewerbungsplan',
      'From vacancy to application plan',
      'Öffne eine Ausbildungsstelle und Apprentice Atlas bereitet den Inhalt verständlich auf. Du kannst Fragen zur konkreten Ausschreibung stellen, deine Voraussetzungen mit den genannten Anforderungen abgleichen und anschließend passende Interviewfragen üben. Aus einer interessanten Stelle wird so ein planbarer nächster Schritt.',
      'Open an apprenticeship and Apprentice Atlas turns the advert into clear information. Ask questions about that specific vacancy, compare your experience with its requirements and practise relevant interview questions. An interesting opportunity becomes a practical next step.',
      [
        'Ausschreibung in klarer, jugendgerechter Sprache verstehen.',
        'Antworten direkt aus der jeweiligen Stelle ableiten.',
        'Stärken und lernbare Lücken für die Bewerbung einordnen.',
        'Interview, Kalender und Erinnerungen passend zur Stelle vorbereiten.',
      ],
      [
        'Understand the advert in clear, youth-friendly language.',
        'Ground answers in the vacancy itself.',
        'Frame relevant strengths and learnable gaps for applying.',
        'Prepare interviews, calendar entries and reminders for the role.',
      ],
    ),
  ],
  'how-it-works': [
    detail(
      'Ein Beispiel vom Signal zur Handlung',
      'An example from signal to action',
      'Aus „Ich repariere gern Dinge“ macht der Atlas mehrere konkrete Suchspuren: Fehlersuche, präzise Handarbeit und sichtbare Ergebnisse. Daraus entstehen passende Suchbegriffe, reale Stellen in unterschiedlichen Arbeitsumgebungen und zwei Angebote, die du anhand ihrer Aufgaben vergleichst.',
      'From “I enjoy repairing things”, the Atlas creates several concrete search trails: fault-finding, precise practical work and visible results. These become useful search terms, real opportunities in different environments and two vacancies you can compare by their duties.',
      [
        'Signal: eine konkrete Erfahrung aus deinem Alltag.',
        'Hypothese: welche Tätigkeit daran interessant war.',
        'Optionen: mindestens zwei unterschiedliche Umgebungen.',
        'Test: Gespräch, Besuch, Aufgabe oder Bewerbung mit Termin.',
      ],
      [
        'Signal: a concrete experience from your life.',
        'Hypothesis: which activity made it interesting.',
        'Options: at least two different environments.',
        'Test: a dated conversation, visit, task or application.',
      ],
    ),
    detail(
      'Erklärbar und veränderbar',
      'Explainable and revisable',
      'Jede vorgeschlagene Spur zeigt, welche Interessen, Suchangaben oder Stelleninformationen dazu geführt haben. Du kannst Interessen ändern, einen anderen Ort wählen oder nach einem Praktikum neue Prioritäten setzen. Deine Ergebnisse entwickeln sich mit deinen Erfahrungen weiter.',
      'Every suggested trail shows which interests, search choices or vacancy details shaped it. You can change interests, choose another location or set new priorities after work experience. Your results develop with your experience.',
      [
        'Eine verständliche Begründung neben jedem Vorschlag.',
        'Offene Fragen werden als nächste Prüfschritte formuliert.',
        'Alternative Wege bleiben erreichbar.',
        'Nutzerfeedback kann eine Spur korrigieren oder entfernen.',
      ],
      [
        'A clear reason beside every suggestion.',
        'Open questions become useful next checks.',
        'Alternative routes remain accessible.',
        'User feedback can correct or remove a trail.',
      ],
    ),
  ],
  app: [
    detail(
      'Ein realistischer Nutzungsmoment',
      'A realistic moment of use',
      'Vor einem Beratungsgespräch speicherst du zwei Stellen, markierst drei Fragen und vergleichst Aufgaben, Lernalltag und Anfahrt. Im Gespräch öffnest du deine übersichtliche Merkliste. Danach trägst du den vereinbarten Betriebsbesuch ein und setzt eine Erinnerung für den nächsten Schritt.',
      'Before a careers conversation, save two vacancies, mark three questions and compare duties, learning and travel. Open your shortlist during the conversation. Afterwards, add the agreed employer visit and set a reminder for the next step.',
      [
        'Kurze Sessions, die sich gut in deinen Alltag einfügen.',
        'Eine private Merkliste für deine interessantesten Stellen.',
        'Vergleiche bleiben nach Kriterien nachvollziehbar.',
        'Eigene Fragen reisen in das nächste Gespräch mit.',
      ],
      [
        'Short sessions that fit around your day.',
        'A private shortlist for your most interesting opportunities.',
        'Comparisons remain traceable to criteria.',
        'Your questions travel into the next conversation.',
      ],
    ),
    detail(
      'Standort und Benachrichtigungen',
      'Location and notifications',
      'Mit deiner Freigabe zeigt die Karte Chancen in deiner Nähe; alternativ wählst du Stadt oder Region manuell. Erinnerungen helfen dir bei selbst gesetzten Fristen, Interviews und nächsten Schritten. Beide Funktionen lassen sich jederzeit anpassen.',
      'With your permission, the map shows opportunities nearby; alternatively, choose a town or region manually. Reminders support the deadlines, interviews and next steps you set. Both features remain under your control.',
      [
        'Chancen im gewählten Umkreis auf der Karte sehen.',
        'Standortfreigabe jederzeit anpassen.',
        'Stadt oder Region jederzeit manuell wechseln.',
        'Erinnerungen passend zu deinen Bewerbungen planen.',
      ],
      [
        'See opportunities within your chosen distance on the map.',
        'Adjust location permission at any time.',
        'Change town or region manually at any time.',
        'Plan reminders around your applications.',
      ],
    ),
  ],
  'product-ai': [
    detail(
      'Ein guter AI-Moment',
      'A good AI moment',
      'Du öffnest eine Stelle und fragst, wie ein typischer Arbeitstag aussieht oder welche Kenntnisse wirklich erwartet werden. Die AI fasst die Ausschreibung verständlich zusammen, nennt die relevante Quelle und schlägt konkrete Rückfragen für Betrieb oder Beratung vor.',
      'Open a vacancy and ask what a typical day looks like or which skills really matter. AI explains the advert in clear language, names the relevant source and suggests specific follow-up questions for the employer or adviser.',
      [
        'Fakten und Vorschläge werden sprachlich getrennt.',
        'Markt und Geltungsbereich stehen bei Systemaussagen.',
        'Quellen führen zur tatsächlich relevanten Stelle.',
        'Fehlende Angaben werden zu konkreten Rückfragen.',
      ],
      [
        'Facts and suggestions are separated in language.',
        'System claims name market and scope.',
        'Sources lead to the relevant evidence.',
        'Missing details become concrete follow-up questions.',
      ],
    ),
    detail(
      'Mit der richtigen Ansprechperson weiterkommen',
      'Continue with the right person',
      'Bei Schutz, Diskriminierung, akuter Belastung, individuellen Rechtsfragen oder verbindlichen Zulassungsentscheidungen führt Apprentice Atlas zu einer passenden menschlichen Anlaufstelle. So bleibt AI-Unterstützung auf Erklären und Vorbereiten konzentriert, während sensible Entscheidungen bei qualifizierten Personen liegen.',
      'For safeguarding, discrimination, acute distress, individual legal questions or binding eligibility decisions, Apprentice Atlas directs people to an appropriate human contact. AI remains focused on explanation and preparation while sensitive decisions stay with qualified people.',
      [
        'Sichtbare Hinweise bei Schutz- und Krisenthemen.',
        'Geeignete Kontaktwege für vertrauliche Unterstützung.',
        'Offizielle Stellen für Vertrags- und Rechtsfragen.',
        'Sichtbarer Weg zu Beratung, Schutzkontakt oder offizieller Stelle.',
      ],
      [
        'Visible guidance for safeguarding and crisis concerns.',
        'Appropriate routes to confidential support.',
        'Official contacts for contract and legal questions.',
        'Visible route to guidance, safeguarding or an official body.',
      ],
    ),
  ],
  'data-sources': [
    detail(
      'Unsere Quellenhierarchie',
      'Our source hierarchy',
      'Für Systemregeln beginnen wir bei der zuständigen Behörde oder dem gesetzlich beauftragten Institut. Für Berufsprofile nutzen wir offizielle Standards und Berufsservices. Redaktionelle Erklärungen dürfen diese Quellen verständlicher machen, aber weder Zuständigkeit noch Einschränkung entfernen.',
      'For system rules we start with the accountable authority or mandated institute. For occupations we use official standards and careers services. Editorial explanation may make those sources easier to understand but must not remove authority or limitation.',
      [
        '1. Gesetz, Regelwerk oder zuständige Primärquelle.',
        '2. Offizieller Berufsstandard oder öffentlicher Careers Service.',
        '3. Eigene redaktionelle Einordnung mit Review.',
        '4. Sekundärquelle nur als Ergänzung, klar benannt.',
      ],
      [
        '1. Law, rule or accountable primary source.',
        '2. Official occupational standard or public careers service.',
        '3. Our reviewed editorial explanation.',
        '4. Clearly labelled secondary source only as context.',
      ],
    ),
    detail(
      'Was bei einem Widerspruch passiert',
      'What happens when sources conflict',
      'Wir wählen nicht still die bequemste Aussage. Redaktion prüft Zuständigkeit, Markt, Datum und mögliche Übergangsregel. Bis zur Klärung wird die Aussage eingeschränkt oder entfernt. Änderungen an wesentlichen Inhalten lösen Review und Cache-Aktualisierung für die betroffene Sprachfassung aus.',
      'We do not silently choose the most convenient claim. Editors check authority, market, date and any transition rule. Until resolved, the statement is limited or removed. Material changes trigger review and cache refresh for the affected language version.',
      [
        'Konflikt und betroffene Seiten inventarisieren.',
        'Primärquelle und fachliche Zuständigkeit klären.',
        'Korrektur mit Datum und Auswirkung dokumentieren.',
        'Übersetzung separat prüfen statt automatisch mitzuändern.',
      ],
      [
        'Inventory the conflict and affected pages.',
        'Resolve primary authority and scope.',
        'Document correction, date and impact.',
        'Review the translation separately rather than changing it blindly.',
      ],
    ),
  ],
  'young-people': [
    detail(
      'Du behältst die Kontrolle',
      'You remain in control',
      'Du kannst interessante Stellen speichern, Suchangaben verändern und Empfehlungen direkt korrigieren. Jede Spur zeigt ihre Begründung, damit du selbst prüfen kannst, ob Aufgaben, Ort und Ausbildungsalltag zu deinen Vorstellungen passen.',
      'Save interesting opportunities, change search choices and correct suggestions directly. Every trail shows its reasoning so you can decide whether the duties, location and training experience fit what you want.',
      [
        'Du kannst mit wenigen Angaben starten und später ergänzen.',
        'Ort, Umkreis und Interessen bleiben veränderbar.',
        'Mehrere Wege lassen sich direkt nebeneinander prüfen.',
        'Du kannst Informationen mit einer Vertrauensperson prüfen.',
      ],
      [
        'Start with a few details and add more later.',
        'Location, distance and interests remain editable.',
        'Compare several routes side by side.',
        'You can check information with a trusted person.',
      ],
    ),
    detail(
      'Beginne in 20 Minuten',
      'Start in 20 minutes',
      'Wähle eine Tätigkeit, die dir Spaß gemacht hat, und beschreibe den interessantesten Teil. Suche zwei Berufsfelder, in denen diese Aufgabe vorkommt, öffne je eine echte Stelle und speichere eine Frage zum Arbeitsalltag. Nach 20 Minuten hast du zwei konkrete Wege für den nächsten Vergleich.',
      'Choose an activity you enjoyed and describe its most interesting part. Find two fields where that task appears, open one real vacancy in each and save a question about daily work. After 20 minutes you have two concrete routes ready to compare.',
      [
        'Eine konkrete Erfahrung auswählen.',
        'Interessanten oder schwierigen Teil benennen.',
        'Zwei unterschiedliche Umgebungen finden.',
        'Einen Realitätstest mit Datum planen.',
      ],
      [
        'Choose one concrete experience.',
        'Name the interesting or difficult part.',
        'Find two different environments.',
        'Plan one dated reality test.',
      ],
    ),
  ],
  schools: [
    detail(
      'Passt in bestehende Beratung und Unterricht',
      'Fits existing guidance and lessons',
      'Ein Pilot knüpft an vorhandene Abläufe an: Jugendliche recherchieren Berufsfelder im Unterricht, bereiten Beratungsgespräche mit einer Merkliste vor oder reflektieren einen Betriebsbesuch. Gemeinsam legen wir fest, an welcher Stelle Apprentice Atlas Zeit spart und Gespräche verbessert.',
      'A pilot connects with existing practice: young people research careers in class, prepare a shortlist before guidance sessions or reflect on an employer visit. Together we define where Apprentice Atlas saves time and improves conversations.',
      [
        'Konkreter Nutzungsmoment und zuständige Person.',
        'Vorhandene Schutz- und Einwilligungsprozesse übernehmen.',
        'Geschützte Wege für vertrauliche Beratungsinhalte.',
        'Zugängliche Alternative für Lernende ohne eigenes Gerät.',
      ],
      [
        'Concrete use moment and accountable person.',
        'Use existing safeguarding and consent processes.',
        'Protected routes for confidential guidance content.',
        'An accessible alternative for learners without a personal device.',
      ],
    ),
    detail(
      'Eine freiwillig teilbare Gesprächsgrundlage',
      'A conversation aid learners choose to share',
      'Jugendliche bringen ihre gespeicherten Stellen, Fragen und Vergleiche freiwillig in ein Gespräch mit. Beratende sehen dadurch schneller, was bereits erkundet wurde und welche Information als Nächstes fehlt. Pilotdaten beantworten ausschließlich die vorab vereinbarten Lernfragen.',
      'Young people choose to bring saved vacancies, questions and comparisons into a conversation. Advisers can quickly see what has already been explored and which information is still needed. Pilot data answers only the learning questions agreed in advance.',
      [
        'Lernende entscheiden, was sie im Gespräch zeigen.',
        'Freie Texte bleiben standardmäßig im persönlichen Arbeitsbereich.',
        'Auswertung konzentriert sich auf Nutzung und Lernziele.',
        'Klarer Kontakt für Korrektur, Vorfall und Rücknahme.',
      ],
      [
        'Learners decide what they bring into the conversation.',
        'Free text stays in the personal workspace by default.',
        'Evaluation focuses on use and learning goals.',
        'Clear contact for correction, incident and withdrawal.',
      ],
    ),
  ],
  parents: [
    detail(
      'Was Sie gemeinsam prüfen können',
      'What you can check together',
      'Öffnen Sie zwei konkrete Optionen und prüfen Sie gemeinsam Wochenablauf, Lernorte, Vergütung oder Kosten, Zugang, Unterstützung und Anschlussmöglichkeiten. Die sichtbaren Quellen und gespeicherten Fragen machen daraus ein sachliches Gespräch über den Alltag hinter jeder Entscheidung.',
      'Open two concrete options and examine weekly life, learning locations, pay or cost, entry, support and progression together. Visible sources and saved questions create a practical conversation about the daily reality behind each choice.',
      [
        'Eine Frage stellen, bevor Sie Rat geben.',
        'Eigene Sorgen offen ansprechen und gemeinsam überprüfen.',
        'Vertrag und Trainingsplan vor Unterschrift lesen.',
        'Bei Schutzthemen die benannten offiziellen Wege nutzen.',
      ],
      [
        'Ask one question before giving advice.',
        'Raise concerns openly and check them together.',
        'Read the contract and training plan before signing.',
        'Use named official routes for safeguarding concerns.',
      ],
    ),
    detail(
      'Datenschutz für Familien',
      'Privacy for families',
      'Die Marketing-Vormerkliste ist ab 16 direkt zugänglich; Jüngere werden zur Anmeldung durch Eltern oder Erziehungsberechtigte geführt. Das ist keine allgemeine Altersfreigabe für jede spätere Produktfunktion. Vor App-Launch werden Einwilligung, Schutz und Rechtsgrundlage je Funktion gesondert geprüft.',
      'Direct marketing waitlist sign-up is available from 16; younger people are directed to a parent or carer. This is not a blanket age decision for every future product feature. Consent, safeguarding and lawful basis will be reviewed separately for each function before app launch.',
      [
        'Keine Werbung auf Basis persönlicher Orientierung.',
        'Analytics nur nach ausdrücklicher Zustimmung.',
        'Standort ist optional.',
        'Löschfristen und Kontaktweg sind veröffentlicht.',
      ],
      [
        'No advertising based on personal exploration.',
        'Analytics only after explicit consent.',
        'Location is optional.',
        'Retention and contact routes are published.',
      ],
    ),
  ],
  pilot: [
    detail(
      'So sieht ein erster Pilot aus',
      'What an initial pilot looks like',
      'Partner und Estopia wählen gemeinsam einen konkreten Nutzungsmoment, etwa die Vorbereitung eines Beratungsgesprächs oder eine Unterrichtseinheit zur Stellensuche. Zielgruppe, Dauer, Unterstützung, Schutzwege, minimale Daten und Auswertung werden vor dem ersten Einsatz schriftlich vereinbart.',
      'The partner and Estopia choose one concrete use case together, such as preparing for a careers conversation or running a vacancy-search lesson. Audience, duration, support, safeguarding routes, minimum data and evaluation are agreed in writing before the first session.',
      [
        'Ein klarer Anwendungsfall mit messbarem Lernziel.',
        'Benannte Verantwortliche auf beiden Seiten.',
        'Briefing für Mitarbeitende, Lernende und Eltern.',
        'Stop- und Eskalationskriterien vor dem ersten Einsatz.',
      ],
      [
        'One clear use case with a measurable learning goal.',
        'Named accountable people on both sides.',
        'Briefing for staff, learners and parents.',
        'Stopping and escalation criteria before first use.',
      ],
    ),
    detail(
      'Was Partner am Ende erhalten',
      'What partners receive at the end',
      'Zum Abschluss erhalten Partner eine nachvollziehbare Auswertung von Nutzung, Rückmeldungen, Lernsignalen, Vorfällen und offenen Fragen. Daraus entsteht eine gemeinsame Entscheidungsgrundlage für Fortführung, Anpassung oder weitere Erprobung.',
      'At close-out, partners receive a traceable evaluation of use, feedback, learning signals, incidents and open questions. This becomes a shared basis for continuing, adapting or testing further.',
      [
        'Vereinbarte Kennzahlen mit Kontext.',
        'Qualitative Rückmeldungen ohne unnötige Identifizierung.',
        'Dokumentierte Abweichungen und negative Ergebnisse.',
        'Empfehlung mit Unsicherheit und verantwortlicher Entscheidung.',
      ],
      [
        'Agreed measures with context.',
        'Qualitative feedback without unnecessary identification.',
        'Documented exceptions and negative findings.',
        'A recommendation with uncertainty and accountable decision.',
      ],
    ),
  ],
  'privacy-safety': [
    detail(
      'Datenflüsse zum Launch',
      'Launch data flows',
      'Die öffentliche Seite kann ohne Konto genutzt werden. Das Partnerformular speichert Organisations- und Kontaktdaten zur Bearbeitung einer Anfrage. Die Vormerkliste speichert E-Mail, Markt, Plattform, Einwilligungsversion und Zeitpunkte. Analytics wird separat und erst nach Zustimmung geladen; Suchbegriffe und Formulartexte werden nicht als Event-Eigenschaften versendet.',
      'The public site works without an account. The partner form stores organisation and contact details to handle an enquiry. The waitlist stores email, market, platform, consent version and timestamps. Analytics loads separately and only after consent; search terms and form messages are not sent as event properties.',
      [
        'Keine CMS- oder Lead-Tabelle über die öffentliche Data API.',
        'Keine Service-Secrets im Browser.',
        'Serverseitige Validierung, Bot-Schutz und Rate-Limits.',
        'Getrennte Staging- und Produktionsprojekte.',
      ],
      [
        'No CMS or lead table through the public Data API.',
        'No service secrets in the browser.',
        'Server-side validation, bot protection and rate limits.',
        'Separate staging and production projects.',
      ],
    ),
    detail(
      'Wenn etwas schiefgeht',
      'When something goes wrong',
      'Sicherheits- und Datenschutzmeldungen werden nach Auswirkung priorisiert. Betroffene Verarbeitung kann gestoppt, ein Schlüssel rotiert oder eine Funktion zurückgenommen werden. Gesetzliche Melde- und Informationspflichten werden mit qualifizierter Beratung geprüft. Vor Launch folgt eine juristische Prüfung einschließlich Kinder-Datenschutz und DPIA-Bedarf.',
      'Security and privacy reports are prioritised by impact. Affected processing can be stopped, a key rotated or a feature withdrawn. Statutory notification duties are assessed with qualified advice. Legal review before launch includes children’s privacy and the need for a DPIA.',
      [
        'security@ für technische Schwachstellen.',
        'privacy@ für Betroffenenrechte und Datenfragen.',
        'Nachvollziehbare Incident-Zeitleiste.',
        'Keine öffentliche Launchfreigabe vor Legal Gate.',
      ],
      [
        'security@ for technical vulnerabilities.',
        'privacy@ for rights and data questions.',
        'Traceable incident timeline.',
        'No public launch approval before the legal gate.',
      ],
    ),
  ],
  'responsible-ai': [
    detail(
      'Risikoprüfung entlang einer Antwort',
      'Risk checks across an answer',
      'Wir prüfen nicht nur das Modell, sondern den gesamten Weg: Welche Eingabe wird verlangt, welcher Quellenkontext wird beigefügt, wie wird Unsicherheit formuliert, welche Handlung schlägt die Oberfläche vor und wie kann ein Fehler gemeldet werden? Ein gutes Modell kann in einem schlechten Interface trotzdem Schaden verursachen.',
      'We assess more than the model: what input is requested, which source context is supplied, how uncertainty is expressed, which action the interface suggests and how an error can be reported. A capable model can still cause harm inside a poor interface.',
      [
        'Testfälle in Deutsch und britischem Englisch.',
        'Vergleich über Geschlecht, Herkunftssignale und Bildungswege.',
        'Besondere Tests für Minderjährige und Schutzsituationen.',
        'Review nach Modell-, Prompt- oder Quellenänderung.',
      ],
      [
        'Tests in German and British English.',
        'Comparison across gender, background signals and education routes.',
        'Specific tests for minors and safeguarding situations.',
        'Review after model, prompt or source changes.',
      ],
    ),
    detail(
      'Beschwerde und Korrektur',
      'Complaint and correction',
      'Nutzende müssen eine problematische Antwort melden können, ohne sie öffentlich zu machen. Das Team trennt faktischen Fehler, unangemessene Empfehlung, Sicherheitsproblem und Produktmissverständnis. Je nach Typ werden Quelle, Prompt, Darstellung oder Funktionsgrenze korrigiert.',
      'People must be able to report a problematic answer without publishing it. The team separates factual error, inappropriate suggestion, safety concern and product misunderstanding. The source, prompt, presentation or feature boundary is corrected according to the issue.',
      [
        'Meldung mit minimal notwendigem Kontext.',
        'Keine Nutzung sensibler Meldungen als Marketingbeispiel.',
        'Wiederholungstest vor Freigabe der Korrektur.',
        'Schwere Muster können zur Abschaltung führen.',
      ],
      [
        'Report with the minimum necessary context.',
        'No use of sensitive reports as marketing examples.',
        'Regression test before releasing a correction.',
        'Serious patterns can lead to withdrawal.',
      ],
    ),
  ],
  'data-principles': [
    detail(
      'Die fünf Regeln vollständig',
      'The five rules in full',
      'Neben Zuständigkeit, Kontext und Korrigierbarkeit gelten Datensparsamkeit und Trennung von Beobachtung und Schlussfolgerung. Wir sammeln nicht vorsorglich alles, was später nützlich sein könnte. Und wir lassen aus einem Nutzungsereignis keine Aussage über Motivation oder Eignung entstehen.',
      'Alongside authority, context and correctability, we apply data minimisation and separation of observation from inference. We do not collect everything just in case it becomes useful. A usage event does not become a claim about motivation or suitability.',
      [
        'Zuständigkeit: Wer darf diese Aussage verbindlich treffen?',
        'Kontext: Wo, wann und für wen gilt sie?',
        'Sparsamkeit: Brauchen wir das Feld wirklich?',
        'Trennung: Was wurde beobachtet, was nur abgeleitet?',
        'Korrigierbarkeit: Wer prüft und ändert?',
      ],
      [
        'Authority: who can make this claim?',
        'Context: where, when and for whom does it apply?',
        'Minimisation: do we genuinely need the field?',
        'Separation: what was observed and what was inferred?',
        'Correctability: who reviews and changes it?',
      ],
    ),
    detail(
      'Praktische Entscheidung',
      'A practical decision',
      'Ein Suchbegriff könnte für Produktanalyse interessant sein, kann aber persönliche Sorgen oder sensible Informationen enthalten. Deshalb messen wir, dass eine Suche stattgefunden hat, nicht den freien Text als Analytics-Eigenschaft. Inhaltliche Verbesserung erfolgt über kontrollierte, freiwillige Forschung statt verdeckter Sammlung.',
      'A search phrase might appear useful for product analysis but can contain personal concerns or sensitive information. We therefore measure that a search happened, not its free text as an analytics property. Content improvement uses controlled voluntary research rather than hidden collection.',
      [
        'Zweck vor Erhebung notieren.',
        'Weniger eingriffsintensive Alternative prüfen.',
        'Zugriff und Löschfrist festlegen.',
        'Neue Nutzung erfordert neue Prüfung.',
      ],
      [
        'Record purpose before collection.',
        'Check a less intrusive alternative.',
        'Set access and retention.',
        'A new use requires a new review.',
      ],
    ),
  ],
  accessibility: [
    detail(
      'Was wir tatsächlich testen',
      'What we actually test',
      'Automatisierte Prüfungen finden nur einen Teil der Barrieren. Zentrale Templates werden zusätzlich vollständig per Tastatur bedient, bei 200 Prozent Zoom geprüft und mit Screenreader auf Struktur, Namen, Statusmeldungen und Fehlerführung kontrolliert. Reduced Motion entfernt den orchestrierten Seitenauftakt und die Weglinienbewegung.',
      'Automated checks find only some barriers. Core templates are also completed by keyboard, checked at 200% zoom and reviewed with a screen reader for structure, names, status messages and error guidance. Reduced Motion removes the orchestrated entrance and route-line movement.',
      [
        'Navigation, Formulare, Consent und Ressourcensuche.',
        '360, 390, 768, 1280 und 1440 Pixel.',
        'Chromium, Firefox und WebKit.',
        'Deutsch und Englisch mit realen Textlängen.',
      ],
      [
        'Navigation, forms, consent and resource search.',
        '360, 390, 768, 1280 and 1440 pixels.',
        'Chromium, Firefox and WebKit.',
        'German and English with real text length.',
      ],
    ),
    detail(
      'Barrieren melden',
      'Report a barrier',
      'Eine hilfreiche Meldung nennt Seite, Aufgabe, verwendetes Gerät oder Hilfsmittel und was statt des erwarteten Ergebnisses geschah. Ein Screenshot ist optional. Teilen Sie keine sensiblen Daten. Wir bestätigen die Meldung und nennen nach Prüfung Auswirkung, Zwischenlösung und nächsten Schritt.',
      'A useful report names the page, task, device or assistive technology and what happened instead of the expected result. A screenshot is optional. Do not share sensitive data. We acknowledge the report and, after review, provide impact, workaround and next action.',
      [
        'E-Mail: accessibility@apprenticeatlas.com.',
        'Kritische Blockade wird vor kosmetischem Fehler priorisiert.',
        'Korrektur erhält einen Regressionstest.',
        'Bekannte Abweichungen erscheinen in der Erklärung.',
      ],
      [
        'Email: accessibility@apprenticeatlas.com.',
        'A critical blocker is prioritised over a cosmetic issue.',
        'The correction receives a regression test.',
        'Known exceptions appear in the statement.',
      ],
    ),
  ],
  impact: [
    detail(
      'Unsere Wirkungskette',
      'Our impact chain',
      'Wir erwarten nicht, dass eine einzelne App-Nutzung direkt einen Ausbildungsabschluss verursacht. Der plausible Weg beginnt kleiner: verständlichere Optionen, bessere Fragen, ein geplanter Realitätstest und informiertere Gespräche. Erst danach können Bewerbungs- und Übergangsergebnisse betrachtet werden – mit den vielen externen Einflüssen, die dazugehören.',
      'We do not expect a single app session to cause apprenticeship completion. The plausible chain starts smaller: clearer options, better questions, a planned reality test and more informed conversations. Application and transition outcomes can be considered later, with the many external influences they contain.',
      [
        'Input: Zugang, Material und Begleitung.',
        'Aktivität: erkunden, vergleichen, fragen, planen.',
        'Frühes Ergebnis: Orientierungskompetenz und Handlung.',
        'Späteres Ergebnis: Übergang, Verbleib und Entwicklung.',
      ],
      [
        'Input: access, material and support.',
        'Activity: explore, compare, question and plan.',
        'Early outcome: career-management skill and action.',
        'Later outcome: transition, persistence and progression.',
      ],
    ),
    detail(
      'Welche Aussage wir nicht machen',
      'Claims we will not make',
      'Wenn 70 Prozent einer Pilotgruppe eine Ressource öffnen, haben wir Nutzung beobachtet – nicht bessere Entscheidungen. Wenn Teilnehmende anschließend klarere Fragen formulieren, kann das ein Lernsignal sein, aber ohne geeignetes Design keine kausale Wirkung. Berichte benennen diese Grenze ausdrücklich.',
      'If 70 per cent of a pilot group open a resource, we have observed use—not better decisions. If participants then formulate clearer questions, that may be a learning signal but is not causal impact without a suitable design. Reports state that boundary explicitly.',
      [
        'Keine Kausalität aus Vorher-Nachher allein.',
        'Keine Erfolgsquote ohne Nenner und Teilnahmebeschreibung.',
        'Keine Ausblendung von Nichtnutzung oder Abbruch.',
        'Keine nachträgliche Änderung der Hauptfrage, um Erfolg zu zeigen.',
      ],
      [
        'No causality from before-and-after alone.',
        'No success rate without denominator and participation context.',
        'No hiding non-use or dropout.',
        'No changing the main question afterwards to manufacture success.',
      ],
    ),
  ],
  about: [
    detail(
      'Verantwortung im Unternehmen',
      'Accountability in the company',
      'Estopia Engineering Ltd verantwortet Produkt und Betrieb. Inhalte brauchen Autor, Reviewer, Quellen und nächstes Prüfdatum. Technische Funktionen erhalten einen Owner, Monitoring und Rücknahmeweg. Für juristische, fachliche und Schutzfragen arbeiten wir vor Launch mit entsprechend qualifizierter externer Prüfung.',
      'Estopia Engineering Ltd is accountable for product and operation. Content requires an author, reviewer, sources and next review date. Technical functions have an owner, monitoring and a withdrawal route. Legal, professional and safeguarding matters receive appropriately qualified external review before launch.',
      [
        'Jede institutionelle Aussage hat eine verantwortliche Person.',
        'Korrekturwege für Inhalt, Datenschutz und Barrierefreiheit.',
        'Getrennte Verantwortlichkeit für Veröffentlichung und Übersetzung.',
        'Pilotentscheidung vor Skalierung.',
      ],
      [
        'Every institutional claim has an accountable owner.',
        'Correction routes for content, privacy and accessibility.',
        'Separate accountability for publication and translation.',
        'Pilot decision before scale.',
      ],
    ),
    detail(
      'Woran wir uns messen lassen wollen',
      'What we want to be judged by',
      'Unser Maßstab ist, ob ein junger Mensch eine Ausbildungsstelle besser versteht, eine gute Frage stellen und den nächsten Schritt selbst planen kann. Verständliche Erklärungen, sichtbare Quellen und geschützte persönliche Daten gehören dabei zusammen.',
      'Our measure is whether a young person understands an apprenticeship better, can ask a useful question and plan the next step independently. Clear explanations, visible sources and protected personal data belong together.',
      [
        'Verständlichkeit mit direktem Zugang zur Originalquelle.',
        'Quellen und Grenzen an der Aussage.',
        'Handlungsfähigkeit als zentrales Lernziel.',
        'Korrektur und Rücknahme als normale Produktarbeit.',
      ],
      [
        'Clarity with direct access to the original source.',
        'Sources and limits beside the claim.',
        'Agency as the central learning goal.',
        'Correction and withdrawal as normal product work.',
      ],
    ),
  ],
  story: [
    detail(
      'Was der Hackathon bewiesen hat',
      'What the hackathon established',
      'Der Prototyp zeigte, dass kartografische Suche, offizielle Ausbildungsdaten und AI-Unterstützung einen verständlichen mobilen Weg bilden können. Daraus entstand eine funktionsfähige TestFlight-App mit Suche, Favoriten, Bewerbungstracking und stellenspezifischer Vorbereitung.',
      'The prototype showed that map discovery, official apprenticeship data and AI support can form a clear mobile journey. It grew into a working TestFlight app with discovery, favourites, application tracking and vacancy-specific preparation.',
      [
        'Offizielle Chancen auf Karte und Liste.',
        'Klartext und Fragen auf Basis der konkreten Stelle.',
        'Private Favoriten und vollständiges Bewerbungstracking.',
        'Zweisprachiger Ablauf für Deutschland und das Vereinigte Königreich.',
      ],
      [
        'Official opportunities on a map and list.',
        'Plain-language guidance and questions grounded in each vacancy.',
        'Private favourites and complete application tracking.',
        'A bilingual journey for Germany and the United Kingdom.',
      ],
    ),
    detail(
      'Bereit für den Einsatz mit Schulen',
      'Preparing for use with schools',
      'Für den Einsatz mit Schulen und Beratung werden Inhalte, Formulare, Datenschutz, Barrierefreiheit und Infrastruktur gemeinsam geprüft. Erste Piloten liefern anschließend die Erfahrungen, mit denen wir Produkt, Begleitung und Betrieb gezielt weiterentwickeln.',
      'For use with schools and advisers, content, forms, privacy, accessibility and infrastructure are reviewed together. Initial pilots will then provide the experience needed to improve the product, support and operation.',
      [
        'Redaktionelle Bibliothek und Quellenreview.',
        'Juristische Prüfung und DPIA-Entscheidung.',
        'Barrierefreiheits- und Security-Abnahme.',
        'Staging, Migration, Smoke-Test und Rollback.',
      ],
      [
        'Editorial library and source review.',
        'Legal review and DPIA decision.',
        'Accessibility and security sign-off.',
        'Staging, migration, smoke test and rollback.',
      ],
    ),
  ],
  press: [
    detail(
      'Belegbare Kernfakten',
      'Verifiable core facts',
      'Apprentice Atlas ist eine zweisprachige, kartenbasierte App für Ausbildung und Apprenticeships in Deutschland und dem Vereinigten Königreich. Sie verbindet offizielle Stellen, verständliche GPT-5.6-Unterstützung, private Favoriten und Bewerbungstracking in einem vollständigen mobilen Ablauf.',
      'Apprentice Atlas is a bilingual, map-based app for apprenticeships in Germany and the United Kingdom. It combines official opportunities, clear GPT-5.6 support, private favourites and application tracking in one complete mobile journey.',
      [
        'Status: funktionsfähige TestFlight-App und Vorbereitung erster Piloten.',
        'Unternehmen: Estopia Engineering Ltd.',
        'Märkte: Deutschland und UK mit systemspezifischen Inhalten.',
        'AI-Funktionen: Klartext, Stellenfragen, Interview- und Skill-Gap-Vorbereitung.',
      ],
      [
        'Status: working TestFlight app and preparation for initial pilots.',
        'Company: Estopia Engineering Ltd.',
        'Markets: Germany and the UK with system-specific content.',
        'AI features: plain language, vacancy Q&A, interview and skill-gap preparation.',
      ],
    ),
    detail(
      'Materialnutzung',
      'Using brand material',
      'Freigegebene Logos und Screens dürfen nicht so verändert werden, dass eine Partnerschaft, Zertifizierung oder Live-Funktion suggeriert wird. Produktaufnahmen werden mit Versionsdatum geliefert. Dokumentarische Fotos erhalten eine eigene Lizenz- und Credit-Angabe.',
      'Approved logos and screenshots must not be altered to imply partnership, certification or a live function. Product captures are supplied with a version date. Documentary photography carries its own licence and credit record.',
      [
        'Produktname nicht abkürzen oder übersetzen.',
        'Keine nachgebauten Screens mit erfundenen Daten.',
        'Credits und Nutzungsumfang beibehalten.',
        'Faktencheck vor Veröffentlichung an press@.',
      ],
      [
        'Do not abbreviate or translate the product name.',
        'No recreated screens with invented data.',
        'Retain credits and permitted use.',
        'Send factual checks to press@ before publication.',
      ],
    ),
  ],
  contact: [
    detail(
      'Damit wir richtig antworten können',
      'Help us route your enquiry',
      'Nennen Sie bei Pilotinteresse Organisation, Rolle, Land, Zielgruppe und den konkreten Nutzungskontext. Für Korrekturen reichen Seitenlink, problematische Aussage und möglichst die bessere Primärquelle. Senden Sie keine sensiblen Daten von Jugendlichen über das allgemeine Kontaktpostfach.',
      'For pilot enquiries, include organisation, role, country, audience and the intended use context. For corrections, provide the page, disputed claim and ideally a better primary source. Do not send sensitive information about young people to the general inbox.',
      [
        'Pilot: Partnerformular.',
        'Inhalt: corrections@apprenticeatlas.com.',
        'Sicherheit: security@apprenticeatlas.com.',
        'Datenschutz: privacy@apprenticeatlas.com.',
      ],
      [
        'Pilot: partner form.',
        'Content: corrections@apprenticeatlas.com.',
        'Security: security@apprenticeatlas.com.',
        'Privacy: privacy@apprenticeatlas.com.',
      ],
    ),
    detail(
      'Was als Nächstes passiert',
      'What happens next',
      'Partneranfragen werden geprüft und einer verantwortlichen Person zugeordnet. Wir versprechen auf dieser Pre-Launch-Seite keine feste Antwortzeit, bevor der Supportbetrieb final besetzt ist. Sicherheits- und Datenschutzmeldungen werden nach möglicher Auswirkung priorisiert.',
      'Partner enquiries are reviewed and assigned to an accountable person. This pre-launch site does not promise a response time before support operations are fully staffed. Security and privacy reports are prioritised by potential impact.',
      [
        'Eingangsbestätigung nach erfolgreicher Formularverarbeitung.',
        'Rückfrage nur zu notwendigen Angaben.',
        'Keine Aufnahme in Newsletter oder CRM ohne eigenen Zweck.',
        'Löschung nach veröffentlichter Retention-Regel.',
      ],
      [
        'Receipt after successful form processing.',
        'Follow-up only for necessary information.',
        'No newsletter or CRM enrolment without a separate purpose.',
        'Deletion under the published retention rule.',
      ],
    ),
  ],
};
