/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    topics: Topic;
    audiences: Audience;
    countries: Country;
    pages: Page;
    articles: Article;
    guides: Guide;
    'career-fields': CareerField;
    'glossary-terms': GlossaryTerm;
    downloads: Download;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    audiences: AudiencesSelect<false> | AudiencesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'career-fields': CareerFieldsSelect<false> | CareerFieldsSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    contact: Contact;
    'store-targets': StoreTarget;
    'social-links': SocialLink;
    'consent-texts': ConsentText;
    'calls-to-action': CallsToAction;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'store-targets': StoreTargetsSelect<false> | StoreTargetsSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    'consent-texts': ConsentTextsSelect<false> | ConsentTextsSelect<true>;
    'calls-to-action': CallsToActionSelect<false> | CallsToActionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'publisher' | 'editor' | 'translator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit: string;
  license: string;
  licenseUrl?: string | null;
  countryContext: 'de' | 'uk' | 'both';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role: string;
  bio: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  key: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiences".
 */
export interface Audience {
  id: number;
  name: string;
  key: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  key: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  title: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Two-digit Atlas chapter label.
   */
  chapterNumber?: string | null;
  author: number | Author;
  reviewer: number | Author;
  reviewedAt: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  audiences: (number | Audience)[];
  countries: (number | Country)[];
  topics?: (number | Topic)[] | null;
  relatedContent?:
    | (
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'guides';
            value: number | Guide;
          }
        | {
            relationTo: 'career-fields';
            value: number | CareerField;
          }
      )[]
    | null;
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  title: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Two-digit Atlas chapter label.
   */
  chapterNumber?: string | null;
  author: number | Author;
  reviewer: number | Author;
  reviewedAt: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  audiences: (number | Audience)[];
  countries: (number | Country)[];
  topics?: (number | Topic)[] | null;
  relatedContent?:
    | (
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'guides';
            value: number | Guide;
          }
        | {
            relationTo: 'career-fields';
            value: number | CareerField;
          }
      )[]
    | null;
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  title: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Two-digit Atlas chapter label.
   */
  chapterNumber?: string | null;
  author: number | Author;
  reviewer: number | Author;
  reviewedAt: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  audiences: (number | Audience)[];
  countries: (number | Country)[];
  topics?: (number | Topic)[] | null;
  relatedContent?:
    | (
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'guides';
            value: number | Guide;
          }
        | {
            relationTo: 'career-fields';
            value: number | CareerField;
          }
      )[]
    | null;
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-fields".
 */
export interface CareerField {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  title: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Two-digit Atlas chapter label.
   */
  chapterNumber?: string | null;
  author: number | Author;
  reviewer: number | Author;
  reviewedAt: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  audiences: (number | Audience)[];
  countries: (number | Country)[];
  topics?: (number | Topic)[] | null;
  relatedContent?:
    | (
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'guides';
            value: number | Guide;
          }
        | {
            relationTo: 'career-fields';
            value: number | CareerField;
          }
      )[]
    | null;
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  term: string;
  definition: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  locale: 'de' | 'en';
  /**
   * Stable shared key linking independent German and English documents.
   */
  translationGroup: string;
  slug: string;
  title: string;
  description: string;
  file: number | Media;
  author: number | Author;
  reviewer: number | Author;
  reviewedAt: string;
  sources: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  audiences: (number | Audience)[];
  countries: (number | Country)[];
  topics?: (number | Topic)[] | null;
  relatedContent?:
    | (
        | {
            relationTo: 'articles';
            value: number | Article;
          }
        | {
            relationTo: 'guides';
            value: number | Guide;
          }
        | {
            relationTo: 'career-fields';
            value: number | CareerField;
          }
      )[]
    | null;
  seo: {
    title: string;
    description: string;
    socialImage: number | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  status: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'audiences';
        value: number | Audience;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'career-fields';
        value: number | CareerField;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  license?: T;
  licenseUrl?: T;
  countryContext?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiences_select".
 */
export interface AudiencesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  chapterNumber?: T;
  author?: T;
  reviewer?: T;
  reviewedAt?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  audiences?: T;
  countries?: T;
  topics?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  chapterNumber?: T;
  author?: T;
  reviewer?: T;
  reviewedAt?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  audiences?: T;
  countries?: T;
  topics?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  chapterNumber?: T;
  author?: T;
  reviewer?: T;
  reviewedAt?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  audiences?: T;
  countries?: T;
  topics?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-fields_select".
 */
export interface CareerFieldsSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  chapterNumber?: T;
  author?: T;
  reviewer?: T;
  reviewedAt?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  audiences?: T;
  countries?: T;
  topics?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  term?: T;
  definition?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  locale?: T;
  translationGroup?: T;
  slug?: T;
  title?: T;
  description?: T;
  file?: T;
  author?: T;
  reviewer?: T;
  reviewedAt?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  audiences?: T;
  countries?: T;
  topics?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    locale: 'de' | 'en';
    label: string;
    href: string;
    parentKey?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyright: string;
  links?:
    | {
        locale: 'de' | 'en';
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  generalEmail: string;
  privacyEmail: string;
  accessibilityEmail: string;
  pressEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-targets".
 */
export interface StoreTarget {
  id: number;
  mode: 'waitlist' | 'stores';
  appleUrl?: string | null;
  googleUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  links?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-texts".
 */
export interface ConsentText {
  id: number;
  version: string;
  locale: 'de' | 'en';
  analyticsTitle: string;
  analyticsBody: string;
  waitlistText: string;
  partnerText: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calls-to-action".
 */
export interface CallsToAction {
  id: number;
  items?:
    | {
        key: string;
        locale: 'de' | 'en';
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        locale?: T;
        label?: T;
        href?: T;
        parentKey?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyright?: T;
  links?:
    | T
    | {
        locale?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  generalEmail?: T;
  privacyEmail?: T;
  accessibilityEmail?: T;
  pressEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-targets_select".
 */
export interface StoreTargetsSelect<T extends boolean = true> {
  mode?: T;
  appleUrl?: T;
  googleUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-texts_select".
 */
export interface ConsentTextsSelect<T extends boolean = true> {
  version?: T;
  locale?: T;
  analyticsTitle?: T;
  analyticsBody?: T;
  waitlistText?: T;
  partnerText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calls-to-action_select".
 */
export interface CallsToActionSelect<T extends boolean = true> {
  items?:
    | T
    | {
        key?: T;
        locale?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'articles';
          value: number | Article;
        } | null)
      | ({
          relationTo: 'guides';
          value: number | Guide;
        } | null)
      | ({
          relationTo: 'career-fields';
          value: number | CareerField;
        } | null)
      | ({
          relationTo: 'glossary-terms';
          value: number | GlossaryTerm;
        } | null)
      | ({
          relationTo: 'downloads';
          value: number | Download;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}